apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    name: backend-deployment
    app: class2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-pod
      app: class2
  template:
    metadata:
      labels:
        name: backend-pod
        app: class2
    spec:
      containers:
        - name: backend-container
          image: paulrojasg/ds3-activity
          ports:
          - containerPort: 8000