apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend-service
    app: class2
spec:
  type: NodePort
  selector:
    name: backend-pod
    app: class2
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
