apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: class2
spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: class2
  ports:
    - port: 6379
      targetPort: 6379
